
name: Blog

on:
  push:
    branches: master

jobs:
  base_deploy:
    name: Deploy blog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 

      - name: CF Deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: BurkeBlog
          template: main.yml
          parameter-overrides: >-
            DBName=${{ secrets.DB_NAME }}
            DBUser=${{ secrets.DB_USER }}
            DBPassword=${{ secrets.DB_PASSWORD }}
